apiVersion: v1
kind: ConfigMap
metadata:
  name: framework-config
  namespace: default
data:
  API_HOST: "0.0.0.0"
  API_PORT: "3000"
  DATABASE_HOST: "postgres-host"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "framework_db"
  S3_HOST: "s3-host"
  S3_REGION: "s3-region"
  S3_BUCKET_NAME: "your-bucket"
