apiVersion: v1
kind: Secret
metadata:
  name: framework-secret
  namespace: default
type: Opaque
stringData:
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "password"
  S3_ACCESS_KEY_ID: "key"
  S3_SECRET_ACCESS_KEY: "secret"
