apiVersion: v1
kind: Service
metadata:
  name: framework-service
  namespace: default
spec:
  selector:
    app: framework
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
