[package]
name = "cf-entity"
version = "0.1.0"
edition = "2024"

[dependencies]
cf-util = {path = "../cf-util"}
tokio = {workspace = true}
dotenvy = {workspace = true}
sea-orm = {workspace = true}
serde = {workspace = true}
regex = "1.10"
utoipa = {workspace = true}